# Generated by Django 5.0.6 on 2024-07-05 14:31

import django.db.models.deletion
import django_userforeignkey.models.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensordata',
            name='alcohol',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='sensordata',
            name='carbon_dioxide',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='sensordata',
            name='carbon_monoxide',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='sensordata',
            name='humidity',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='sensordata',
            name='hydrogen',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='sensordata',
            name='lpg_gas',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='sensordata',
            name='productID',
            field=django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sensordata',
            name='smoke',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='sensordata',
            name='temperature',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='sensordata',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
