# Generated by Django 5.0.6 on 2024-07-05 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0003_customuser_groups_customuser_user_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensordata',
            name='air_quality_index',
            field=models.FloatField(default=0),
        ),
    ]
