# Generated by Django 5.0.6 on 2024-10-17 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0005_healthtip_riskalert'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthtip',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='riskalert',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
