# Generated by Django 5.0.6 on 2024-10-29 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0006_healthtip_timestamp_riskalert_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email_address',
            field=models.EmailField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='full_name',
            field=models.CharField(max_length=255),
        ),
    ]
